### PR TITLE
[Base: checkpoints_plugin] Retrieve checkpoint by name

### PR DESCRIPTION
**Pull request by absolutelyNoWarranty**
Implement retrieval of checkpoint output by name. Rename get_from_checkpoint to get_by_checkpoint_index

### CODE REVIEW

**Comment by SoluMilken** [comment]
Need an example for adding checkpoint given name. (pipe.add_checkpoint('name_1'))

**Comment by SoluMilken** [comment]
這裡的改變? : 
1. pipe.add_checkpoint 可以提供名字
2. intermediate.get_from_checkpoint -> intermediate.get_by_checkpoint_index
3. intermediate 的 get item 可以給 string, 
他會幫你根據 add_checkpoint 時給的名字, 回傳相對應的intermediate.

**Comment by stegben** [comment]
What's the benefit of retrieving by name?

**Comment by SoluMilken** [comment]
@absolutelyNoWarranty

**Comment by absolutelyNoWarranty** [comment]
More convenient.

**Comment by stegben** [comment]
什麼情況下會需要連 call 兩次？沒有的話應該要擋掉

**Pull request closed without merging**
